(function(){
  const Store=window.DWK_STORE,U=window.DWK_UTILS,UI=window.DWK_UI,E=window.DWK_DATA.enums;
  const app=document.getElementById('app'),title=document.getElementById('pageTitle'),modal=document.getElementById('modalBackdrop'),modalForm=document.getElementById('modalForm'),modalBody=document.getElementById('modalBody');
  let currentPage='dashboard',filters={},modalHandler=null,activeRecognition=null;
  const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
  const voiceButton=name=>SpeechRecognition?`<button type="button" class="voice-button" data-voice-target="f_${name}" aria-label="语音输入" title="点击开始语音输入" aria-pressed="false">🎙</button>`:'';
  const field=(name,label,type='text',value='',extra='')=>{
    const attrs=extra.replace('full','');
    const control=type==='textarea'?`<textarea id="f_${name}" name="${name}" ${attrs}>${U.escape(value||'')}</textarea>`:`<input class="input" id="f_${name}" name="${name}" type="${type}" value="${U.escape(value??'')}" ${attrs}>`;
    const acceptsVoice=type==='text'||type==='textarea';
    return `<div class="field ${extra.includes('full')?'full':''}"><label for="f_${name}">${label}</label>${acceptsVoice?`<div class="voice-input ${type==='textarea'?'voice-textarea':''}">${control}${voiceButton(name)}</div>`:control}</div>`;
  };
  const select=(name,label,options,value,extra='')=>`<div class="field ${extra.includes('full')?'full':''}"><label for="f_${name}">${label}</label><select id="f_${name}" name="${name}" ${extra.replace('full','')}>${options.map(x=>`<option value="${U.escape(x.value??x)}" ${(x.value??x)===value?'selected':''}>${U.escape(x.label??x)}</option>`).join('')}</select></div>`;
  const formData=()=>Object.fromEntries(new FormData(modalForm).entries());
  const numberFields=(obj,keys)=>{keys.forEach(k=>obj[k]=Number(obj[k]||0));return obj};
  const get=(arr,id)=>arr.find(x=>x.id===id);
  function toast(msg,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=msg;document.getElementById('toastContainer').append(el);setTimeout(()=>el.remove(),2600)}
  function render(){const data=Store.get();title.textContent=UI.titles[currentPage];document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===currentPage));app.innerHTML=UI.render(currentPage,data,filters);app.focus({preventScroll:true});if(currentPage==='dashboard')requestAnimationFrame(()=>UI.drawWeightChart(data))}
  function go(page){currentPage=page;document.getElementById('sidebar').classList.remove('open');document.getElementById('sidebarOverlay').classList.remove('open');render();window.scrollTo({top:0,behavior:'smooth'})}
  function openModal(titleText,html,onSubmit){document.getElementById('modalTitle').textContent=titleText;modalBody.innerHTML=`<div class="form-grid">${html}</div>`;modalHandler=onSubmit;modal.hidden=false;setTimeout(()=>modalBody.querySelector('input,select,textarea')?.focus(),50)}
  function stopVoiceInput(){if(activeRecognition){activeRecognition.recognition.stop();activeRecognition=null}}
  function startVoiceInput(button){
    const target=document.getElementById(button.dataset.voiceTarget);if(!target)return;
    if(activeRecognition){const same=activeRecognition.button===button;stopVoiceInput();if(same)return}
    const recognition=new SpeechRecognition(),original=target.value,separator=original?(target.tagName==='TEXTAREA'?'\n':' '):'';
    recognition.lang='zh-CN';recognition.continuous=true;recognition.interimResults=true;
    activeRecognition={recognition,button};button.classList.add('listening');button.setAttribute('aria-pressed','true');button.title='正在聆听，点击停止';
    recognition.onresult=e=>{let transcript='';for(let i=0;i<e.results.length;i++)transcript+=e.results[i][0].transcript;target.value=original+separator+transcript;target.dispatchEvent(new Event('input',{bubbles:true}))};
    recognition.onerror=e=>{if(e.error!=='aborted'&&e.error!=='no-speech')toast(e.error==='not-allowed'||e.error==='service-not-allowed'?'无法使用麦克风，请在浏览器中允许麦克风权限':'语音识别失败，请重试',true)};
    recognition.onend=()=>{button.classList.remove('listening');button.setAttribute('aria-pressed','false');button.title='点击开始语音输入';if(activeRecognition?.recognition===recognition)activeRecognition=null};
    try{recognition.start()}catch(err){recognition.onend();toast('语音识别暂时无法启动，请重试',true)}
  }
  function closeModal(){stopVoiceInput();modal.hidden=true;modalHandler=null;modalForm.reset()}
  function commit(fn,msg='已保存'){Store.update(fn);closeModal();render();toast(msg)}
  function confirmDelete(msg,fn){if(confirm(msg)){Store.update(fn);render();toast('已删除')}}
  function adjustAccount(data,tx,multiplier){const a=get(data.accounts,tx.accountId);if(a)a.balance+=Number(tx.amount||0)*(tx.type==='收入'?1:-1)*multiplier}
  function transactionModal(existing){
    const x=existing||{date:U.today(),type:'支出',amount:'',category:'餐饮',accountId:Store.get().accounts[0].id,note:''};
    openModal(existing?'编辑收支记录':'添加收支记录',field('date','日期','date',x.date,'required')+select('type','类型',['收入','支出'],x.type)+field('amount','金额（元）','number',x.amount,'min="0.01" step="0.01" required')+select('category','分类',[...new Set([...E.expenseCategories,...E.incomeCategories])],x.category)+select('accountId','计入账户',Store.get().accounts.map(a=>({value:a.id,label:a.name})),x.accountId)+field('note','备注','textarea',x.note,'full'),()=>{const v=numberFields(formData(),['amount']);commit(d=>{if(existing){adjustAccount(d,existing,-1);Object.assign(existing,v);adjustAccount(d,existing,1)}else{const tx={id:U.uid('tx'),...v};d.transactions.push(tx);adjustAccount(d,tx,1)}},existing?'收支记录已更新':'收支已添加，账户余额已同步')});
  }
  function healthModal(existing){const x=existing||{date:U.today(),morningWeight:'',eveningWeight:'',breakfast:'',lunch:'',dinner:'',sleep:'',cpap:'',condition:'良好',note:''};openModal(existing?'编辑健康记录':'新增健康记录',field('date','日期','date',x.date,'required')+field('morningWeight','早晨体重（kg）','number',x.morningWeight,'min="0" step="0.1"')+field('eveningWeight','晚上体重（kg）','number',x.eveningWeight,'min="0" step="0.1"')+field('sleep','睡眠小时','number',x.sleep,'min="0" max="24" step="0.1"')+field('cpap','CPAP 使用小时','number',x.cpap,'min="0" max="24" step="0.1"')+select('condition','身体状态',['良好','一般','疲惫','不适'],x.condition)+field('breakfast','早餐','text',x.breakfast)+field('lunch','午餐','text',x.lunch)+field('dinner','晚餐','text',x.dinner)+field('note','备注','textarea',x.note,'full'),()=>{const v=numberFields(formData(),['morningWeight','eveningWeight','sleep','cpap']);commit(d=>existing?Object.assign(existing,v):d.health.push({id:U.uid('h'),...v}),existing?'健康记录已更新':'健康记录已添加')})}
  function fuelModal(existing){const x=existing||{date:U.today(),amount:'',liters:'',mileage:'',note:''};openModal(existing?'编辑加油记录':'新增加油记录',field('date','加油日期','date',x.date,'required')+field('amount','加油金额（元）','number',x.amount,'min="0" step="0.01" required')+field('liters','加油升数（L）','number',x.liters,'min="0.01" step="0.01" required')+field('mileage','本次里程（km）','number',x.mileage,'min="1" step="1" required')+field('note','备注','textarea',x.note,'full'),()=>{const v=numberFields(formData(),['amount','liters','mileage']);commit(d=>existing?Object.assign(existing,v):d.motor.fuelLogs.push({id:U.uid('f'),...v}),existing?'加油记录已更新':'加油记录已添加')})}
  function maintModal(existing){const x=existing||{date:U.today(),mileage:Store.get().motor.currentMileage,item:'',nextMileage:'',note:''};openModal(existing?'编辑保养记录':'新增保养记录',field('date','保养日期','date',x.date,'required')+field('mileage','保养里程（km）','number',x.mileage,'min="0" step="1" required')+field('item','保养项目','text',x.item,'required')+field('nextMileage','下次保养里程（km）','number',x.nextMileage,'min="0" step="1" required')+field('note','备注','textarea',x.note,'full'),()=>{const v=numberFields(formData(),['mileage','nextMileage']);commit(d=>existing?Object.assign(existing,v):d.motor.maintenanceLogs.push({id:U.uid('m'),...v}),existing?'保养记录已更新':'保养记录已添加')})}
  function ideaModal(existing){const x=existing||{name:'',category:'',stage:'想法',priority:'中',cost:0,nextAction:'',note:''};openModal(existing?'编辑点子':'新增点子',field('name','名称','text',x.name,'required')+field('category','分类','text',x.category,'required')+select('stage','当前阶段',E.ideaStages,x.stage)+select('priority','优先级',E.priorities,x.priority)+field('cost','预计成本（元）','number',x.cost,'min="0" step="1"')+field('nextAction','下一步行动','text',x.nextAction,'required')+field('note','备注','textarea',x.note,'full'),()=>{const v=numberFields(formData(),['cost']);commit(d=>existing?Object.assign(existing,v):d.ideas.push({id:U.uid('i'),...v}),existing?'点子已更新':'点子已添加')})}
  function todoModal(existing){const x=existing||{title:'',status:'今天必须完成',dueDate:U.today(),note:''};openModal(existing?'编辑待办':'新增待办',field('title','待办内容','text',x.title,'required')+select('status','分类',E.todoStatus,x.status)+field('dueDate','计划日期','date',x.dueDate)+field('note','备注','textarea',x.note,'full')+(existing?`<div class="full"><button type="button" class="button danger small" data-action="todo-delete-modal" data-id="${existing.id}">删除这条待办</button></div>`:''),()=>{const v=formData();commit(d=>existing?Object.assign(existing,v):d.todos.push({id:U.uid('t'),...v}),existing?'待办已更新':'待办已添加')})}
  function handleAction(action,id,value){const d=Store.get();switch(action){
    case'goto':go(id);break;case'health-add':healthModal();break;case'health-edit':healthModal(get(d.health,id));break;case'health-delete':confirmDelete('确定删除这条健康记录吗？',x=>x.health=x.health.filter(i=>i.id!==id));break;
    case'account-edit':{const a=get(d.accounts,id);openModal('修改账户余额',field('balance',`${a.name}余额（元）`,'number',a.balance,'step="0.01" required')+`<p class="muted full">直接修改余额不会创建收支流水。</p>`,()=>{const v=formData();commit(()=>a.balance=Number(v.balance),'账户余额已更新')});break}
    case'tx-add':transactionModal();break;case'tx-edit':transactionModal(get(d.transactions,id));break;case'tx-delete':{const tx=get(d.transactions,id);confirmDelete('删除流水后将同步还原对应账户余额，确定继续吗？',x=>{adjustAccount(x,tx,-1);x.transactions=x.transactions.filter(i=>i.id!==id)});break}
    case'finance-settings':openModal('最低生活费设置',field('monthlyMinCost','每月最低生活费（元）','number',d.settings.monthlyMinCost,'min="1" step="100" required'),()=>{const v=formData();commit(x=>x.settings.monthlyMinCost=Number(v.monthlyMinCost),'生活费设置已更新')});break;
    case'finance-filter':filters.financeType=value;render();break;case'motor-settings':openModal('车辆信息',field('currentMileage','当前总里程（km）','number',d.motor.currentMileage,'min="0" step="1" required')+field('insuranceExpiry','保险到期日期','date',d.motor.insuranceExpiry,'required')+field('notes','车辆备注','textarea',d.motor.notes,'full'),()=>{const v=formData();commit(x=>Object.assign(x.motor,{...v,currentMileage:Number(v.currentMileage)}),'车辆信息已更新')});break;
    case'fuel-add':fuelModal();break;case'fuel-edit':fuelModal(get(d.motor.fuelLogs,id));break;case'fuel-delete':confirmDelete('确定删除这条加油记录吗？',x=>x.motor.fuelLogs=x.motor.fuelLogs.filter(i=>i.id!==id));break;
    case'maint-add':maintModal();break;case'maint-edit':maintModal(get(d.motor.maintenanceLogs,id));break;case'maint-delete':confirmDelete('确定删除这条保养记录吗？',x=>x.motor.maintenanceLogs=x.motor.maintenanceLogs.filter(i=>i.id!==id));break;
    case'idea-add':ideaModal();break;case'idea-edit':ideaModal(get(d.ideas,id));break;case'idea-delete':confirmDelete('确定删除这个点子吗？',x=>x.ideas=x.ideas.filter(i=>i.id!==id));break;case'idea-filter':filters.ideaPriority=value;render();break;
    case'todo-add':todoModal();break;case'todo-edit':todoModal(get(d.todos,id));break;case'todo-delete-modal':closeModal();confirmDelete('确定删除这条待办吗？',x=>x.todos=x.todos.filter(i=>i.id!==id));break;
  }}
  document.querySelector('.nav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)go(b.dataset.page)});
  app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)handleAction(b.dataset.action,b.dataset.id,b.dataset.value)});
  app.addEventListener('change',e=>{if(e.target.dataset.action==='java-status'){Store.update(d=>get(d.java,e.target.dataset.id).status=e.target.value);render();toast('学习状态已更新')}});
  app.addEventListener('submit',e=>{if(e.target.id==='quickSettings'){e.preventDefault();const v=Object.fromEntries(new FormData(e.target).entries());Store.update(d=>Object.assign(d.settings,{leaveDate:v.leaveDate,monthlyMinCost:Number(v.monthlyMinCost)}));render();toast('快速设置已保存')}});
  modalBody.addEventListener('click',e=>{const button=e.target.closest('[data-voice-target]');if(button)startVoiceInput(button)});
  modalForm.addEventListener('submit',e=>{e.preventDefault();if(modalHandler)modalHandler()});
  document.getElementById('modalClose').onclick=closeModal;document.getElementById('modalCancel').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
  document.getElementById('menuButton').onclick=()=>{document.getElementById('sidebar').classList.add('open');document.getElementById('sidebarOverlay').classList.add('open')};document.getElementById('sidebarOverlay').onclick=()=>{document.getElementById('sidebar').classList.remove('open');document.getElementById('sidebarOverlay').classList.remove('open')};
  document.getElementById('exportButton').onclick=()=>{const blob=new Blob([Store.exportJSON()],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`DWK-Life-OS-备份-${U.today()}.json`;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('数据已导出为 JSON')};
  document.getElementById('resetButton').onclick=()=>{if(confirm('确定恢复初始演示数据吗？当前数据将被覆盖，建议先导出备份。')){Store.reset();filters={};render();toast('已恢复初始演示数据')}};
  document.getElementById('importButton').onclick=()=>document.getElementById('importFile').click();document.getElementById('importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const text=await file.text();if(!confirm('导入将覆盖当前所有数据，确定继续吗？'))return;Store.importJSON(text);filters={};render();toast('数据导入成功')}catch(err){toast(err.message,true)}finally{e.target.value=''}});
  window.addEventListener('resize',()=>{if(currentPage==='dashboard')UI.drawWeightChart(Store.get())});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});
  document.getElementById('todayText').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());
  Store.load();render();
})();
