(function(){
  const U=window.DWK_UTILS;
  const tag=v=>`<span class="tag ${U.statusClass(v)}">${U.escape(v)}</span>`;
  const empty=t=>`<div class="empty">${t}</div>`;
  const table=(heads,rows)=>`<div class="card table-card"><div class="table-wrap"><table class="data-table"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${heads.length}">${empty('暂无记录')}</td></tr>`}</tbody></table></div></div>`;
  const stat=(label,value,note,color='var(--blue)',icon='●')=>`<article class="stat-card" style="--accent:${color}"><div class="stat-label"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="stat-note">${note}</div></article>`;
  const btn=(label,action,id='',kind='text-button')=>`<button class="${kind}" data-action="${action}" data-id="${id}">${label}</button>`;

  const UI={
    titles:{dashboard:'首页总览',health:'健康记录',finance:'财务管理',motor:'摩托车管理',java:'Java 学习',ideas:'点子管理',todos:'待办事项',passwords:'账户密码'},
    render(page,data,filters={}){return this[page](data,filters)},
    dashboard(data){
      const f=U.financeStats(data),w=U.weightStats(data.health),done=data.java.filter(x=>x.status==='已完成').length,jp=Math.round(done/data.java.length*100);
      const todayTodos=data.todos.filter(x=>x.status==='今天必须完成');
      const ideas=[...data.ideas].filter(x=>x.stage!=='已完成').sort((a,b)=>({高:0,中:1,低:2}[a.priority]-({高:0,中:1,低:2}[b.priority]))).slice(0,4);
      const fuel=data.motor.fuelLogs,liters=U.sum(fuel,'liters'),miles=U.sum(fuel,'mileage'),fuelAvg=liters?liters/miles*100:0;
      return `<section class="stats-grid grid">
        ${stat('最新体重',w.latest?U.number(w.latest)+' kg':'暂无记录',w.change===null?'等待更多数据':`较上次 ${w.change>0?'+':''}${U.number(w.change)} kg`,'var(--cyan)','♥')}
        ${stat('可直接使用资金',U.formatMoney(f.available),`约可支撑 ${U.number(f.supportMonths)} 个月`,'var(--green)','¥')}
        ${stat('离职剩余工作日',U.workdaysUntil(data.settings.leaveDate)+' 天',`目标日期 ${U.formatDate(data.settings.leaveDate)}`,'var(--orange)','⌛')}
        ${stat('摩托车当前里程',Number(data.motor.currentMileage).toLocaleString()+' km',`平均油耗 ${U.number(fuelAvg,2)} L/100km`,'var(--purple)','◇')}
      </section>
      <section class="dashboard-grid grid">
        <article class="card"><div class="card-head"><h3>最近 7 天体重趋势</h3><span>单位：kg</span></div><canvas class="chart" id="weightChart" aria-label="最近7天体重趋势图"></canvas></article>
        <article class="card"><div class="card-head"><h3>本月收入与支出</h3><span>${U.monthKey()}</span></div><div class="finance-bars"><div class="bar-row"><span>收入</span><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,f.income/Math.max(f.income,f.expense,1)*100)}%"></div></div><strong>${U.formatMoney(f.income)}</strong></div><div class="bar-row"><span>支出</span><div class="bar-track"><div class="bar-fill expense" style="width:${Math.min(100,f.expense/Math.max(f.income,f.expense,1)*100)}%"></div></div><strong>${U.formatMoney(f.expense)}</strong></div></div><div class="muted">本月结余：${U.formatMoney(f.income-f.expense)}</div></article>
        <article class="card"><div class="card-head"><h3>Java 学习进度</h3>${btn('查看路线 →','goto','java')}</div><div class="progress-ring-wrap"><div class="progress-ring" style="--p:${jp}"><strong>${jp}%</strong></div><div class="progress-detail"><div class="dot-line"><span>已完成</span><b>${done} / ${data.java.length}</b></div><div class="dot-line"><span>学习中</span><b>${data.java.filter(x=>x.status==='学习中').length} 项</b></div><div class="dot-line"><span>需要复习</span><b>${data.java.filter(x=>x.status==='需要复习').length} 项</b></div></div></div></article>
        <article class="card"><div class="card-head"><h3>今日待办</h3>${btn('全部待办 →','goto','todos')}</div>${todayTodos.length?`<div class="simple-list">${todayTodos.map(x=>`<div class="list-row"><span class="tag tag-red">必做</span><div class="grow"><strong>${U.escape(x.title)}</strong><small>${U.escape(x.note||'今天完成')}</small></div></div>`).join('')}</div>`:empty('今天没有必须完成的事项')}</article>
        <article class="card"><div class="card-head"><h3>最近副业点子</h3>${btn('管理点子 →','goto','ideas')}</div><div class="simple-list">${ideas.map(x=>`<div class="list-row"><span class="tag ${U.statusClass(x.priority)}">${x.priority}</span><div class="grow"><strong>${U.escape(x.name)}</strong><small>${U.escape(x.nextAction)}</small></div></div>`).join('')}</div></article>
        <article class="card"><div class="card-head"><h3>快速设置</h3><span>影响首页统计</span></div><form id="quickSettings" class="settings-strip"><div class="field"><label>计划离职日期</label><input class="input" type="date" name="leaveDate" value="${data.settings.leaveDate}" required></div><div class="field"><label>每月最低生活费</label><input class="input" type="number" min="0" step="100" name="monthlyMinCost" value="${data.settings.monthlyMinCost}" required></div><button class="button secondary" type="submit">保存设置</button></form></article>
      </section>`;
    },
    health(data){
      const s=U.weightStats(data.health),rows=[...data.health].sort((a,b)=>b.date.localeCompare(a.date));
      const trs=rows.map((x,i)=>{const prev=rows[i+1],delta=prev&&x.morningWeight&&prev.morningWeight?Number(x.morningWeight)-Number(prev.morningWeight):null;const meals=`早：${x.breakfast||'—'} / 午：${x.lunch||'—'} / 晚：${x.dinner||'—'}`;return `<tr><td>${U.formatDate(x.date)}</td><td><b>${U.number(x.morningWeight)} kg</b>${delta!==null?` <small class="${delta>0?'negative':'positive'}">${delta>0?'+':''}${U.number(delta)}</small>`:''}</td><td>${U.number(x.eveningWeight)} kg</td><td title="${U.escape(meals)}">${U.escape(meals)}</td><td>${U.number(x.sleep)} h</td><td>${U.number(x.cpap)} h</td><td>${tag(x.condition||'未填写')}</td><td title="${U.escape(x.note)}">${U.escape(x.note||'—')}</td><td><div class="row-actions">${btn('编辑','health-edit',x.id)}${btn('删除','health-delete',x.id,'text-button danger')}</div></td></tr>`}).join('');
      return `<div class="section-head"><div><h2>身体数据与生活记录</h2><p>记录晨晚体重、饮食、睡眠与 CPAP 使用情况</p></div><button class="button primary" data-action="health-add">＋ 新增健康记录</button></div><section class="stats-grid grid">${stat('最新晨重',s.latest?U.number(s.latest)+' kg':'—','以最近记录为准','var(--cyan)','♥')}${stat('相比上次',s.change===null?'—':`${s.change>0?'+':''}${U.number(s.change)} kg`,'晨重变化','var(--blue)','↕')}${stat('最近 7 天平均',s.avg7?U.number(s.avg7)+' kg':'—','按有记录日期计算','var(--green)','≈')}${stat('最近 30 天变化',s.change30===null?'数据不足':`${s.change30>0?'+':''}${U.number(s.change30)} kg`,'需至少一条约30天前记录','var(--orange)','↗')}</section>${table(['日期','早晨体重','晚上体重','饮食','睡眠','CPAP','状态','备注','操作'],trs)}`;
    },
    finance(data,filters){
      const f=U.financeStats(data),type=filters.financeType||'全部';let tx=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date));if(type!=='全部')tx=tx.filter(x=>x.type===type);
      const cats={};data.transactions.filter(x=>x.type==='支出'&&x.date.startsWith(U.monthKey())).forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount));const max=Math.max(...Object.values(cats),1);
      const accounts=data.accounts.map(a=>`<article class="account-card"><div class="account-top"><span>${U.escape(a.name)}</span>${a.refundable?tag('押金'):a.available?tag('可用'):tag('不计入')}</div><strong>${U.formatMoney(a.balance)}</strong>${btn('修改余额','account-edit',a.id)}</article>`).join('');
      const trs=tx.map(x=>`<tr><td>${U.formatDate(x.date)}</td><td>${tag(x.type)}</td><td><b class="${x.type==='收入'?'positive':'negative'}">${x.type==='收入'?'+':'-'}${U.formatMoney(x.amount)}</b></td><td>${U.escape(x.category)}</td><td>${U.escape(data.accounts.find(a=>a.id===x.accountId)?.name||'—')}</td><td>${U.escape(x.note||'—')}</td><td><div class="row-actions">${btn('编辑','tx-edit',x.id)}${btn('删除','tx-delete',x.id,'text-button danger')}</div></td></tr>`).join('');
      return `<div class="section-head"><div><h2>账户与收支</h2><p>父母尚未归还款项不计入可用资产；押金单独统计</p></div><div class="section-actions"><button class="button secondary" data-action="finance-settings">生活费设置</button><button class="button primary" data-action="tx-add">＋ 添加收支</button></div></div><section class="account-grid grid">${accounts}</section><section class="stats-grid grid">${stat('可直接使用资金',U.formatMoney(f.available),'仅工商、邮储和现金','var(--green)','¥')}${stat('可退押金',U.formatMoney(f.deposit),'不计入直接可用资金','var(--purple)','↩')}${stat('本月支出',U.formatMoney(f.expense),`本月收入 ${U.formatMoney(f.income)}`,'var(--orange)','↓')}${stat('资金可支撑',U.number(f.supportMonths)+' 个月',`最低生活费 ${U.formatMoney(data.settings.monthlyMinCost)}/月`,'var(--blue)','⌛')}</section><section class="two-col grid" style="margin-bottom:18px"><article class="card"><div class="card-head"><h3>本月支出分类</h3><span>共 ${U.formatMoney(f.expense)}</span></div>${Object.keys(cats).length?`<div class="category-bars">${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="category-row"><span>${U.escape(k)}</span><div class="bar-track"><div class="bar-fill expense" style="width:${v/max*100}%"></div></div><b>${U.formatMoney(v)}</b></div>`).join('')}</div>`:empty('本月暂无支出')}</article><article class="card"><div class="card-head"><h3>计算口径</h3><span>清晰、不重复</span></div><div class="simple-list"><div class="list-row"><div class="grow"><strong>直接可用</strong><small>工商银行 + 邮储银行 + 现金</small></div></div><div class="list-row"><div class="grow"><strong>可退押金</strong><small>单独展示，不计入当前可用资金</small></div></div><div class="list-row"><div class="grow"><strong>父母未归还款项</strong><small>未设为账户，因此不会计入资产</small></div></div></div></article></section><div class="toolbar"><div class="filter-tabs">${['全部','收入','支出'].map(x=>`<button class="filter-tab ${type===x?'active':''}" data-action="finance-filter" data-value="${x}">${x}</button>`).join('')}</div><span class="muted">共 ${tx.length} 条流水</span></div>${table(['日期','类型','金额','分类','账户','备注','操作'],trs)}`;
    },
    motor(data){
      const m=data.motor,fuels=[...m.fuelLogs].sort((a,b)=>b.date.localeCompare(a.date)),maint=[...m.maintenanceLogs].sort((a,b)=>b.date.localeCompare(a.date));const liters=U.sum(fuels,'liters'),miles=U.sum(fuels,'mileage'),avg=liters?liters/miles*100:0;const lastMaint=maint[0],remain=lastMaint?Number(lastMaint.nextMileage)-Number(m.currentMileage):null;
      const frows=fuels.map(x=>`<tr><td>${U.formatDate(x.date)}</td><td>${U.formatMoney(x.amount)}</td><td>${U.number(x.liters,2)} L</td><td>${U.number(x.mileage)} km</td><td>${U.number(Number(x.liters)/Number(x.mileage)*100,2)} L/100km</td><td>${U.escape(x.note||'—')}</td><td><div class="row-actions">${btn('编辑','fuel-edit',x.id)}${btn('删除','fuel-delete',x.id,'text-button danger')}</div></td></tr>`).join('');
      const mrows=maint.map(x=>`<tr><td>${U.formatDate(x.date)}</td><td>${Number(x.mileage).toLocaleString()} km</td><td>${U.escape(x.item)}</td><td>${Number(x.nextMileage).toLocaleString()} km</td><td>${U.escape(x.note||'—')}</td><td><div class="row-actions">${btn('编辑','maint-edit',x.id)}${btn('删除','maint-delete',x.id,'text-button danger')}</div></td></tr>`).join('');
      return `<div class="section-head"><div><h2>骑行与养护</h2><p>集中管理里程、油耗、保养与保险信息</p></div><div class="section-actions"><button class="button secondary" data-action="motor-settings">车辆信息</button><button class="button secondary" data-action="maint-add">＋ 保养记录</button><button class="button primary" data-action="fuel-add">＋ 加油记录</button></div></div><section class="stats-grid grid">${stat('当前总里程',Number(m.currentMileage).toLocaleString()+' km','车辆累计里程','var(--purple)','◇')}${stat('平均油耗',U.number(avg,2)+' L/100km',`基于 ${fuels.length} 次加油记录`,'var(--cyan)','≈')}${stat('距下次保养',remain===null?'未设置':Math.max(0,remain).toLocaleString()+' km',remain!==null&&remain<0?`已超出 ${Math.abs(remain)} km`:`目标 ${lastMaint?Number(lastMaint.nextMileage).toLocaleString():'—'} km`,'var(--orange)','⚙')}${stat('保险到期',U.formatDate(m.insuranceExpiry),`${Math.max(0,U.daysBetween(U.today(),m.insuranceExpiry))} 天后`,'var(--blue)','▣')}</section><div class="section-head"><div><h2>加油记录</h2><p>平均油耗按总加油升数 ÷ 总本次里程 × 100 计算</p></div></div>${table(['日期','金额','升数','本次里程','本次油耗','备注','操作'],frows)}<div class="section-head" style="margin-top:24px"><div><h2>保养记录</h2><p>${U.escape(m.notes||'暂无车辆备注')}</p></div></div>${table(['日期','保养里程','保养项目','下次保养里程','备注','操作'],mrows)}`;
    },
    java(data){
      const counts=Object.fromEntries(window.DWK_DATA.enums.javaStatus.map(s=>[s,data.java.filter(x=>x.status===s).length]));const done=counts['已完成'],percent=Math.round(done/data.java.length*100);
      return `<div class="section-head"><div><h2>Java 学习路线</h2><p>从语法基础逐步进入工程化与 Spring Boot</p></div><span class="tag tag-blue">已完成 ${done}/${data.java.length}</span></div><section class="stats-grid grid">${stat('总体进度',percent+'%','按已完成项目计算','var(--blue)','J')}${stat('学习中',counts['学习中']+' 项','保持每日推进','var(--cyan)','▶')}${stat('需要复习',counts['需要复习']+' 项','安排间隔复习','var(--orange)','↻')}${stat('未开始',counts['未开始']+' 项','后续学习内容','var(--muted)','○')}</section><section class="java-grid grid">${data.java.map((x,i)=>`<article class="java-item"><div><span class="order">${String(i+1).padStart(2,'0')}</span><strong>${U.escape(x.name)}</strong></div><select data-action="java-status" data-id="${x.id}" aria-label="${U.escape(x.name)}学习状态">${window.DWK_DATA.enums.javaStatus.map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></article>`).join('')}</section>`;
    },
    ideas(data,filters){
      const p=filters.ideaPriority||'全部';let list=[...data.ideas].sort((a,b)=>({高:0,中:1,低:2}[a.priority]-({高:0,中:1,低:2}[b.priority])));if(p!=='全部')list=list.filter(x=>x.priority===p);
      const rows=list.map(x=>`<tr><td><b>${U.escape(x.name)}</b></td><td>${U.escape(x.category)}</td><td>${tag(x.stage)}</td><td>${tag(x.priority)}</td><td>${U.formatMoney(x.cost)}</td><td>${U.escape(x.nextAction||'—')}</td><td><div class="row-actions">${btn('编辑','idea-edit',x.id)}${btn('删除','idea-delete',x.id,'text-button danger')}</div></td></tr>`).join('');
      return `<div class="section-head"><div><h2>副业与产品点子</h2><p>记录方向、成本、优先级和下一步行动</p></div><button class="button primary" data-action="idea-add">＋ 新增点子</button></div><div class="toolbar"><div class="filter-tabs">${['全部','高','中','低'].map(x=>`<button class="filter-tab ${p===x?'active':''}" data-action="idea-filter" data-value="${x}">${x}${x==='全部'?'':'优先级'}</button>`).join('')}</div><span class="muted">当前显示 ${list.length} 个点子</span></div>${table(['名称','分类','当前阶段','优先级','预计成本','下一步行动','操作'],rows)}`;
    },
    todos(data){
      const statuses=window.DWK_DATA.enums.todoStatus;
      return `<div class="section-head"><div><h2>待办事项</h2><p>按处理时机分类，点击卡片即可编辑</p></div><button class="button primary" data-action="todo-add">＋ 新增待办</button></div><section class="kanban grid">${statuses.map(s=>{const list=data.todos.filter(x=>x.status===s);return `<div class="kanban-col"><div class="kanban-head">${s}<span>${list.length}</span></div>${list.map(x=>`<article class="todo-card ${s==='已完成'?'completed':''}" data-action="todo-edit" data-id="${x.id}"><strong>${U.escape(x.title)}</strong><small>${x.dueDate?U.formatDate(x.dueDate):'未设置日期'}${x.note?' · '+U.escape(x.note):''}</small></article>`).join('')||empty('暂无事项')}</div>`}).join('')}</section>`;
    },
    passwords(){
      const vault=window.DWK_VAULT,status=vault.status();
      if(status==='unsupported')return `<section class="vault-gate card"><div class="vault-icon">!</div><h2>当前环境无法启用密码库</h2><p>请使用 HTTPS 地址或较新版本的 Chrome、Edge、Firefox、Safari 打开。</p></section>`;
      if(status==='new')return `<section class="vault-gate card"><div class="vault-icon">▣</div><h2>创建本地加密密码库</h2><p>所有内容会先加密再保存在当前浏览器。主密码无法找回，请务必记住。</p><form id="vaultSetup" class="vault-form"><div class="field"><label for="vaultMaster">设置主密码（至少 8 位）</label><input class="input" id="vaultMaster" name="password" type="password" minlength="8" autocomplete="new-password" required></div><div class="field"><label for="vaultConfirm">确认主密码</label><input class="input" id="vaultConfirm" name="confirm" type="password" minlength="8" autocomplete="new-password" required></div><button class="button primary" type="submit">创建密码库</button></form></section>`;
      if(status==='locked')return `<section class="vault-gate card"><div class="vault-icon">▣</div><h2>密码库已锁定</h2><p>输入主密码解锁。刷新页面或闲置 10 分钟后会自动锁定。</p><form id="vaultUnlock" class="vault-form"><div class="field"><label for="vaultMaster">主密码</label><input class="input" id="vaultMaster" name="password" type="password" autocomplete="current-password" required></div><button class="button primary" type="submit">解锁</button></form></section>`;
      const entries=vault.getEntries().sort((a,b)=>a.site.localeCompare(b.site,'zh-CN'));
      return `<div class="section-head"><div><h2>账户密码库</h2><p>AES-GCM 本地加密 · 闲置 10 分钟自动锁定</p></div><div class="section-actions"><button class="button secondary" data-action="password-lock">锁定</button><button class="button primary" data-action="password-add">＋ 新增账户</button></div></div><div class="toolbar"><input class="input vault-search" type="search" placeholder="搜索网站、账号或标签" data-action="password-search" aria-label="搜索密码库"><span class="muted">共 ${entries.length} 个账户</span></div><section class="password-grid grid">${entries.map(x=>`<article class="password-card" data-search="${U.escape(`${x.site} ${x.username} ${x.tags||''}`.toLowerCase())}"><div class="password-card-head"><div><strong>${U.escape(x.site)}</strong>${x.url&&/^https?:\/\//i.test(x.url)?`<a href="${U.escape(x.url)}" target="_blank" rel="noopener noreferrer">打开网站 ↗</a>`:''}</div><span>${U.escape(x.tags||'未分类')}</span></div><div class="credential-row"><small>账号</small><code>${U.escape(x.username)}</code><button class="text-button" data-action="password-copy" data-id="${x.id}" data-value="username">复制</button></div><div class="credential-row"><small>密码</small><code data-password-value="${x.id}">••••••••••••</code><button class="text-button" data-action="password-toggle" data-id="${x.id}">显示</button><button class="text-button" data-action="password-copy" data-id="${x.id}" data-value="password">复制</button></div>${x.note?`<p>${U.escape(x.note)}</p>`:''}<div class="password-actions"><button class="text-button" data-action="password-edit" data-id="${x.id}">编辑</button><button class="text-button danger" data-action="password-delete" data-id="${x.id}">删除</button></div></article>`).join('')||empty('还没有保存账户，点击“新增账户”开始')}</section>`;
    },
    drawWeightChart(data){
      const canvas=document.getElementById('weightChart');if(!canvas)return;const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const W=rect.width,H=rect.height,p={l:38,r:16,t:18,b:28};
      const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d.toISOString().slice(0,10)});const vals=days.map(day=>{const x=data.health.find(h=>h.date===day);return x?Number(x.morningWeight)||null:null});const nums=vals.filter(Boolean);c.clearRect(0,0,W,H);c.font='11px sans-serif';c.fillStyle='#8290a3';
      if(!nums.length){c.textAlign='center';c.fillText('最近 7 天暂无晨重记录',W/2,H/2);return}const min=Math.floor(Math.min(...nums)-1),max=Math.ceil(Math.max(...nums)+1),range=max-min||1;
      for(let i=0;i<4;i++){const y=p.t+(H-p.t-p.b)*i/3;c.strokeStyle='#222c38';c.beginPath();c.moveTo(p.l,y);c.lineTo(W-p.r,y);c.stroke();c.textAlign='right';c.fillText(U.number(max-range*i/3),p.l-7,y+4)}
      const pts=vals.map((v,i)=>v?{x:p.l+(W-p.l-p.r)*i/6,y:p.t+(max-v)/range*(H-p.t-p.b),v}:null);c.strokeStyle='#4f8cff';c.lineWidth=2.5;c.beginPath();let started=false;pts.forEach(pt=>{if(!pt){started=false;return}if(!started){c.moveTo(pt.x,pt.y);started=true}else c.lineTo(pt.x,pt.y)});c.stroke();pts.forEach(pt=>{if(!pt)return;c.fillStyle='#0f151d';c.strokeStyle='#6ea1ff';c.lineWidth=2;c.beginPath();c.arc(pt.x,pt.y,4,0,Math.PI*2);c.fill();c.stroke()});c.fillStyle='#8290a3';c.textAlign='center';days.forEach((d,i)=>c.fillText(d.slice(5).replace('-','/'),p.l+(W-p.l-p.r)*i/6,H-7));
    }
  };
  window.DWK_UI=UI;
})();
