(function(){
  const Store=window.DWK_STORE,U=window.DWK_UTILS,UI=window.DWK_UI,D=window.DWK_DATA,Vault=window.DWK_VAULT;
  const app=document.getElementById('app'),title=document.getElementById('pageTitle'),modal=document.getElementById('modalBackdrop'),modalBody=document.getElementById('modalBody'),modalTitle=document.getElementById('modalTitle'),modalForm=document.getElementById('modalForm');
  let page='dashboard',filters={},handler=null,pendingImport=null;
  const field=(name,label,type='text',value='',attrs='')=>`<label class="field ${attrs.includes('full')?'full':''}"><span>${label}</span>${type==='textarea'?`<textarea name="${name}" ${attrs.replace('full','')}>${U.escape(value??'')}</textarea>`:`<input class="input" name="${name}" type="${type}" value="${U.escape(value??'')}" ${attrs.replace('full','')}>`}</label>`;
  const select=(name,label,items,value,attrs='')=>`<label class="field ${attrs.includes('full')?'full':''}"><span>${label}</span><select name="${name}" ${attrs.replace('full','')}>${items.map(x=>{const v=typeof x==='object'?x.value:x,l=typeof x==='object'?x.label:x;return`<option value="${U.escape(v)}" ${String(v)===String(value)?'selected':''}>${U.escape(l)}</option>`}).join('')}</select></label>`;
  const check=(name,label,value)=>`<label class="check-field"><input type="checkbox" name="${name}" ${value?'checked':''}> ${label}</label>`;
  const val=()=>{const f=new FormData(modalForm),o=Object.fromEntries(f.entries());modalForm.querySelectorAll('input[type=checkbox]').forEach(x=>o[x.name]=x.checked);return o};
  const nums=(o,keys)=>{keys.forEach(k=>o[k]=o[k]===''?0:Number(o[k]));return o};
  const get=(a,id)=>a.find(x=>x.id===id);
  function toast(message,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;document.getElementById('toastContainer').appendChild(el);setTimeout(()=>el.remove(),3500)}
  function openModal(t,html,onSubmit,size=''){modalTitle.textContent=t;modalBody.innerHTML=`<div class="form-grid ${size}">${html}</div>`;handler=onSubmit;modal.hidden=false;modal.querySelector('input,select,textarea')?.focus()}
  function closeModal(){modal.hidden=true;handler=null;pendingImport=null;modalForm.reset()}
  async function commit(mutator,message){try{await Store.update(mutator);render();toast(message)}catch(err){toast(err.message,true)}}
  function confirmDelete(message,mutator){if(confirm(message))commit(mutator,'已删除')}
  function render(){const d=Store.get();if(!d)return;title.textContent=UI.titles[page];document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));app.innerHTML=UI[page](d,filters);requestAnimationFrame(()=>UI.draw(page,d,filters));document.getElementById('sidebar').classList.remove('open');document.getElementById('sidebarOverlay').classList.remove('open')}
  function go(p){page=p;render();history.replaceState(null,'','#'+p);app.focus()}
  function healthModal(x){x=x||{date:U.today(),morningWeight:'',eveningWeight:'',sleep:'',cpap:'',water:'',steps:'',exerciseMinutes:'',mood:'良好',condition:'良好',cpapUsed:false,goalCompleted:false,breakfast:'',lunch:'',dinner:'',note:''};openModal(x.id?'编辑健康记录':'新增健康记录',field('date','日期','date',x.date,'required')+field('morningWeight','晨重（kg）','number',x.morningWeight,'step="0.1" min="0"')+field('eveningWeight','晚重（kg）','number',x.eveningWeight,'step="0.1" min="0"')+field('sleep','睡眠（小时）','number',x.sleep,'step="0.1" min="0" max="24"')+field('cpap','CPAP（小时）','number',x.cpap,'step="0.1" min="0" max="24"')+field('water','饮水量（ml）','number',x.water,'min="0"')+field('steps','步数','number',x.steps,'min="0"')+field('exerciseMinutes','运动分钟','number',x.exerciseMinutes,'min="0"')+select('mood','心情',D.enums.moods,x.mood)+select('condition','身体状态',['良好','一般','疲惫','不适'],x.condition)+check('cpapUsed','当日使用 CPAP',x.cpapUsed)+check('goalCompleted','当日目标已完成',x.goalCompleted)+field('breakfast','早餐','text',x.breakfast)+field('lunch','午餐','text',x.lunch)+field('dinner','晚餐','text',x.dinner)+field('note','备注','textarea',x.note,'full'),()=>{const o=nums(val(),['morningWeight','eveningWeight','sleep','cpap','water','steps','exerciseMinutes']);return commit(d=>{const old=get(d.health,x.id);old?Object.assign(old,o):d.health.push({id:U.uid('h'),...o})},x.id?'健康记录已更新':'健康记录已新增')})}
  function txModal(x){x=x||{date:U.today(),type:'支出',amount:'',category:'餐饮',accountId:Store.get().accounts[0]?.id,large:false,note:''};openModal(x.id?'编辑收支':'添加收支',field('date','日期','date',x.date,'required')+select('type','类型',['支出','收入'],x.type)+field('amount','金额','number',x.amount,'min="0.01" step="0.01" required')+select('category','分类',[...D.enums.expenseCategories,...D.enums.incomeCategories],x.category)+select('accountId','账户',Store.get().accounts.map(a=>({value:a.id,label:a.name})),x.accountId)+check('large','标记为大额支出',x.large)+field('note','备注','textarea',x.note,'full'),()=>{const o=nums(val(),['amount']);return commit(d=>{const apply=(tx,k)=>{const a=get(d.accounts,tx.accountId);if(a&&!a.receivable)a.balance+=(tx.type==='收入'?1:-1)*tx.amount*k};const old=get(d.transactions,x.id);if(old){apply(old,-1);Object.assign(old,o);apply(old,1)}else{const n={id:U.uid('tx'),...o};d.transactions.push(n);apply(n,1)}},x.id?'流水已更新':'流水已添加')})}
  function rideModal(x){x=x||{date:U.today(),from:'',to:'',distance:'',durationMinutes:'',note:''};openModal(x.id?'编辑骑行':'新增骑行',field('date','日期','date',x.date,'required')+field('from','出发地','text',x.from,'required')+field('to','目的地','text',x.to,'required')+field('distance','单次里程（km）','number',x.distance,'min="0" step="0.1" required')+field('durationMinutes','时长（分钟）','number',x.durationMinutes,'min="0" required')+field('note','备注','textarea',x.note,'full'),()=>{const o=nums(val(),['distance','durationMinutes']);return commit(d=>{const old=get(d.rides,x.id);if(old)Object.assign(old,o);else{d.rides.push({id:U.uid('r'),...o});d.motor.currentMileage=Number(d.motor.currentMileage)+o.distance}},x.id?'骑行已更新':'骑行已新增，当前里程已同步')})}
  function fuelModal(x){x=x||{date:U.today(),amount:'',liters:'',mileage:'',station:'',fuelType:'92#',unitPrice:'',note:''};openModal(x.id?'编辑加油':'新增加油',field('date','日期','date',x.date,'required')+field('amount','金额（元）','number',x.amount,'step="0.01" min="0" required')+field('liters','升数（L）','number',x.liters,'step="0.01" min="0.01" required')+field('mileage','本次里程（km）','number',x.mileage,'step="0.1" min="0.1" required')+field('station','加油站','text',x.station)+field('fuelType','油品型号','text',x.fuelType)+field('unitPrice','单价','number',x.unitPrice,'step="0.01" min="0"')+field('note','备注','textarea',x.note,'full'),()=>{const o=nums(val(),['amount','liters','mileage','unitPrice']);if(!o.unitPrice)o.unitPrice=o.liters?o.amount/o.liters:0;return commit(d=>{const old=get(d.fuelLogs,x.id);old?Object.assign(old,o):d.fuelLogs.push({id:U.uid('f'),...o})},x.id?'加油记录已更新':'加油记录已新增')})}
  function serviceModal(x,kind='保养'){x=x||{date:U.today(),mileage:Store.get().motor.currentMileage,item:'',description:'',nextMileage:'',cost:'',note:''};openModal(x.id?'编辑记录':'新增车辆记录',select('kind','类型',['保养','故障','维修'],kind)+field('date','日期','date',x.date,'required')+field('mileage','里程','number',x.mileage,'min="0"')+field('item','项目 / 描述','text',x.item||x.description,'required')+field('nextMileage','下次保养里程','number',x.nextMileage,'min="0"')+field('cost','费用','number',x.cost,'min="0" step="0.01"')+field('note','备注','textarea',x.note,'full'),()=>{const o=nums(val(),['mileage','nextMileage','cost']),map={保养:'maintenanceLogs',故障:'faults',维修:'repairs'},target=map[o.kind];delete o.kind;o.description=o.item;return commit(d=>{Object.values(map).forEach(k=>d[k]=d[k].filter(i=>i.id!==x.id));d[target].push({id:x.id||U.uid('svc'),...o})},x.id?'车辆记录已更新':'车辆记录已新增')})}
  function javaLogModal(x){x=x||{date:U.today(),startTime:'19:00',endTime:'20:00',content:'',independent:false,needReview:false,problem:'',code:'',error:'',solution:'',nextContent:''};openModal(x.id?'编辑学习记录':'新增学习记录',field('date','日期','date',x.date,'required')+field('startTime','开始时间','time',x.startTime,'required')+field('endTime','结束时间','time',x.endTime,'required')+field('content','今日学习内容','text',x.content,'required')+check('independent','独立完成',x.independent)+check('needReview','需要复习',x.needReview)+field('problem','遇到的问题','textarea',x.problem,'full')+field('code','示例代码','textarea',x.code,'full')+field('error','错误信息','textarea',x.error,'full')+field('solution','解决方法','textarea',x.solution,'full')+field('nextContent','下一步学习内容','textarea',x.nextContent,'full'),()=>{const o=val(),[sh,sm]=o.startTime.split(':').map(Number),[eh,em]=o.endTime.split(':').map(Number);o.durationMinutes=eh*60+em-sh*60-sm;if(o.durationMinutes<0)o.durationMinutes+=1440;if(!o.durationMinutes)throw new Error('学习结束时间必须晚于开始时间');return commit(d=>{const old=get(d.javaLogs,x.id);old?Object.assign(old,o):d.javaLogs.push({id:U.uid('jl'),...o});if(o.needReview){const topic=d.javaTopics.find(t=>o.content.includes(t.name));if(topic)topic.status='需要复习'}},x.id?'学习记录已更新':'学习记录已新增')},'wide')}
  function ideaModal(x){x=x||{name:'',category:'',stage:'想法',priority:'中',nextAction:'',interest:3,difficulty:3,estimatedCost:3,monetization:3,abilityMatch:3,nextClarity:3,note:''};const score=(n,l)=>field(n,`${l}（1–5）`,'number',x[n],'min="1" max="5" required');openModal(x.id?'编辑点子':'新增点子',field('name','点子名称','text',x.name,'required')+field('category','分类','text',x.category,'required')+select('stage','看板状态',D.enums.ideaStages,x.stage)+select('priority','优先级',D.enums.priorities,x.priority)+score('interest','兴趣程度')+score('difficulty','实现难度')+score('estimatedCost','预计成本')+score('monetization','变现可能')+score('abilityMatch','能力匹配度')+score('nextClarity','下一步明确程度')+field('nextAction','可执行的下一步动作','text',x.nextAction,'required full')+field('note','备注','textarea',x.note,'full'),()=>{const o=nums(val(),['interest','difficulty','estimatedCost','monetization','abilityMatch','nextClarity']);o.updatedAt=new Date().toISOString();return commit(d=>{const old=get(d.ideas,x.id);old?Object.assign(old,o):d.ideas.push({id:U.uid('i'),createdAt:new Date().toISOString(),...o})},x.id?'点子已更新':'点子已新增')})}
  function todoModal(x){x=x||{title:'',status:'未完成',dueDate:U.today(),priority:'中',module:'通用',estimatedMinutes:'',actualMinutes:'',repeat:'无',completedAt:'',delayReason:'',note:''};openModal(x.id?'编辑待办':'新增待办',field('title','任务内容','text',x.title,'required full')+select('status','状态',['未完成','已完成'],x.status)+field('dueDate','截止日期','date',x.dueDate)+select('priority','优先级',D.enums.priorities,x.priority)+select('module','所属模块',D.enums.todoModules,x.module)+field('estimatedMinutes','预计耗时（分钟）','number',x.estimatedMinutes,'min="0"')+field('actualMinutes','实际耗时（分钟）','number',x.actualMinutes,'min="0"')+select('repeat','重复任务',['无','每天','每周','每月'],x.repeat)+field('completedAt','完成时间','datetime-local',x.completedAt?.slice(0,16)||'')+field('delayReason','延期原因','textarea',x.delayReason,'full')+field('note','备注','textarea',x.note,'full'),()=>{const o=nums(val(),['estimatedMinutes','actualMinutes']);if(o.status==='已完成'&&!o.completedAt)o.completedAt=new Date().toISOString();return commit(d=>{const old=get(d.todos,x.id);old?Object.assign(old,o):d.todos.push({id:U.uid('t'),...o})},x.id?'待办已更新':'待办已新增')})}
  function passwordModal(x){x=x||{site:'',url:'',username:'',password:'',tags:'',note:''};openModal(x.id?'编辑账户':'新增账户',field('site','网站 / 服务','text',x.site,'required')+field('url','网址','url',x.url)+field('username','账号','text',x.username,'required')+field('password','密码','text',x.password,'required')+field('tags','标签','text',x.tags)+field('note','备注','textarea',x.note,'full'),async()=>{await Vault.upsert({id:x.id||U.uid('pw'),...val()});closeModal();render();toast('加密账户已保存')})}
  function dashboardConfig(){const cfg=Store.config(),labels={latestWeight:'最新体重',avg7Weight:'7天平均体重',change30Weight:'30天体重变化',availableFunds:'可用资金',budgetRate:'预算使用率',supportMonths:'资金支撑月份',mileage:'摩托车里程',maintenance:'保养剩余',javaWeek:'本周Java',javaProgress:'Java进度',leaveCountdown:'离职剩余工作日',todayTodos:'今日必做',topIdeas:'高分点子',state7:'7天状态'};openModal('配置仪表盘',`<div class="full dashboard-config">${cfg.dashboardOrder.map(k=>`<div class="list-row"><input type="checkbox" name="card_${k}" ${cfg.hiddenCards.includes(k)?'':'checked'}><span class="grow">${labels[k]||k}</span><button type="button" class="text-button" data-action="card-up" data-id="${k}">↑</button><button type="button" class="text-button" data-action="card-down" data-id="${k}">↓</button></div>`).join('')}</div>`,()=>{const o=val(),hidden=cfg.dashboardOrder.filter(k=>!o['card_'+k]);Store.saveConfig({hiddenCards:hidden});closeModal();render();toast('仪表盘设置已保存')})}
  async function importPreview(file){try{const text=await file.text(),check=Store.validateImport(text);pendingImport=text;openModal('数据导入预览',`<div class="full"><p><b>数据版本：</b>V${check.version}　<b>范围：</b>${check.scope}</p><div class="preview-grid">${Object.entries(check.counts).map(([k,v])=>`<span>${k}<b>${v}</b></span>`).join('')}</div><p class="muted">导入前会自动备份当前数据。同 ID 记录按所选方式处理。</p></div>${select('mode','导入方式',[{value:'merge',label:'合并（同 ID 覆盖）'},{value:'replace',label:'完整替换'}],'merge')}`,async()=>{const mode=val().mode;await Store.importJSON(pendingImport,mode);closeModal();render();toast('数据导入完成')})}catch(err){toast(err.message,true)}}
  app.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id,d=Store.get(),kind=b.dataset.kind;try{switch(a){
    case'health-add':healthModal();break;case'health-edit':healthModal(get(d.health,id));break;case'health-delete':confirmDelete('确定删除这条健康记录？',x=>x.health=x.health.filter(i=>i.id!==id));break;case'health-range':filters.healthRange=+b.dataset.value;render();break;
    case'account-edit':{const x=get(d.accounts,id);openModal('修改账户余额',field('balance',x.name+'余额','number',x.balance,'step="0.01" required'),()=>commit(z=>get(z.accounts,id).balance=Number(val().balance),'账户余额已更新'));break}case'tx-add':txModal();break;case'tx-edit':txModal(get(d.transactions,id));break;case'tx-delete':confirmDelete('删除流水会还原对应账户余额，继续？',z=>{const x=get(z.transactions,id),ac=get(z.accounts,x.accountId);if(ac&&!ac.receivable)ac.balance-=(x.type==='收入'?1:-1)*x.amount;z.transactions=z.transactions.filter(i=>i.id!==id)});break;
    case'finance-settings':{const s=d.settings;openModal('预算与现金流参数',field('monthlyBudget','月度总预算','number',s.monthlyBudget,'min="0"')+field('monthlyMinCost','每月最低生活费','number',s.monthlyMinCost,'min="0"')+field('monthlyNormalCost','每月正常生活费','number',s.monthlyNormalCost,'min="0"')+field('rent','房租','number',s.rent,'min="0"')+field('mortgage','房贷','number',s.mortgage,'min="0"')+field('transportCost','交通费用','number',s.transportCost,'min="0"')+field('motorCost','摩托车费用','number',s.motorCost,'min="0"')+field('expectedIncome','预计月收入','number',s.expectedIncome,'min="0"')+field('oneTimeExpense','一次性支出','number',U.sum(s.oneTimeExpenses||[],'amount'),'min="0"'),()=>{const o=nums(val(),['monthlyBudget','monthlyMinCost','monthlyNormalCost','rent','mortgage','transportCost','motorCost','expectedIncome','oneTimeExpense']);return commit(z=>Object.assign(z.settings,o,{oneTimeExpenses:o.oneTimeExpense?[{id:'once',amount:o.oneTimeExpense}]:[]}), '财务参数已更新')});break}
    case'budget-manage':openModal('支出分类预算',d.categoryBudgets.map((x,i)=>field('b_'+i,x.category+'（设为 0 删除）','number',x.amount,'min="0"')).join('')+select('newCategory','新增分类',D.enums.expenseCategories,'餐饮')+field('newAmount','新增预算','number','0','min="0"'),()=>commit(z=>{const o=val();z.categoryBudgets.forEach((x,i)=>x.amount=+o['b_'+i]);z.categoryBudgets=z.categoryBudgets.filter(x=>x.amount>0);if(+o.newAmount){const old=z.categoryBudgets.find(x=>x.category===o.newCategory);old?old.amount=+o.newAmount:z.categoryBudgets.push({id:U.uid('cb'),category:o.newCategory,amount:+o.newAmount})}},'分类预算已保存'));break;
    case'fixed-manage':openModal('固定支出与收入计划',`<div class="full"><p>固定支出（金额设为 0 删除）</p>${d.fixedExpenses.map((x,i)=>field('fx_'+i,x.name,'number',x.amount,'min="0"')).join('')}<p>收入计划（金额设为 0 删除）</p>${d.incomePlans.map((x,i)=>field('ip_'+i,x.name,'number',x.amount,'min="0"')).join('')}</div>`+field('newFixedName','新增固定支出名称')+field('newFixedAmount','金额','number','0')+field('newIncomeName','新增收入计划名称')+field('newIncomeAmount','金额','number','0'),()=>commit(z=>{const o=val();z.fixedExpenses.forEach((x,i)=>x.amount=+o['fx_'+i]);z.incomePlans.forEach((x,i)=>x.amount=+o['ip_'+i]);z.fixedExpenses=z.fixedExpenses.filter(x=>x.amount>0);z.incomePlans=z.incomePlans.filter(x=>x.amount>0);if(o.newFixedName&&+o.newFixedAmount)z.fixedExpenses.push({id:U.uid('fx'),name:o.newFixedName,amount:+o.newFixedAmount});if(o.newIncomeName&&+o.newIncomeAmount)z.incomePlans.push({id:U.uid('ip'),name:o.newIncomeName,amount:+o.newIncomeAmount})},'固定收支已保存'));break;case'cash-scenario':filters.cashScenario=b.dataset.value;render();break;
    case'motor-settings':openModal('车辆信息',field('currentMileage','当前总里程','number',d.motor.currentMileage,'min="0"')+field('insuranceExpiry','保险到期','date',d.motor.insuranceExpiry)+field('inspectionExpiry','年检到期','date',d.motor.inspectionExpiry)+field('notes','备注','textarea',d.motor.notes,'full'),()=>{const o=val();o.currentMileage=+o.currentMileage;return commit(z=>Object.assign(z.motor,o),'车辆信息已更新')});break;case'ride-add':rideModal();break;case'ride-edit':rideModal(get(d.rides,id));break;case'ride-delete':confirmDelete('确定删除骑行记录？',z=>z.rides=z.rides.filter(i=>i.id!==id));break;case'fuel-add':fuelModal();break;case'fuel-edit':fuelModal(get(d.fuelLogs,id));break;case'fuel-delete':confirmDelete('确定删除加油记录？',z=>z.fuelLogs=z.fuelLogs.filter(i=>i.id!==id));break;case'service-add':serviceModal();break;case'service-edit':serviceModal(get(({保养:d.maintenanceLogs,故障:d.faults,维修:d.repairs})[kind],id),kind);break;case'service-delete':confirmDelete('确定删除车辆记录？',z=>{const k={保养:'maintenanceLogs',故障:'faults',维修:'repairs'}[kind];z[k]=z[k].filter(i=>i.id!==id)});break;case'checklist-reset':app.querySelectorAll('[data-action=ride-check]').forEach(x=>x.checked=false);break;
    case'java-log-add':javaLogModal();break;case'java-log-edit':javaLogModal(get(d.javaLogs,id));break;case'java-log-delete':confirmDelete('确定删除学习记录？',z=>z.javaLogs=z.javaLogs.filter(i=>i.id!==id));break;
    case'idea-add':ideaModal();break;case'idea-edit':ideaModal(get(d.ideas,id));break;case'idea-delete':confirmDelete('低分点子也不会自动删除。确定手动删除？',z=>z.ideas=z.ideas.filter(i=>i.id!==id));break;
    case'todo-view':filters.todoView=b.dataset.value;render();break;case'todo-add':todoModal();break;case'todo-edit':todoModal(get(d.todos,id));break;case'todo-delete':confirmDelete('确定删除待办？',z=>z.todos=z.todos.filter(i=>i.id!==id));break;case'todo-toggle':await commit(z=>{const x=get(z.todos,id);x.status=x.status==='已完成'?'未完成':'已完成';x.completedAt=x.status==='已完成'?new Date().toISOString():''},'待办状态已更新');break;
    case'dashboard-config':dashboardConfig();break;case'card-up':case'card-down':{const cfg=Store.config(),i=cfg.dashboardOrder.indexOf(id),j=a==='card-up'?i-1:i+1;if(j>=0&&j<cfg.dashboardOrder.length){[cfg.dashboardOrder[i],cfg.dashboardOrder[j]]=[cfg.dashboardOrder[j],cfg.dashboardOrder[i]];Store.saveConfig({dashboardOrder:cfg.dashboardOrder});dashboardConfig()}break}
    case'review-export':{const start=filters.reviewStart||U.startOfWeek(),end=filters.reviewEnd||U.dateOffset(6,start),s=U.weeklySummary(d,start,end),r=d.weeklyReviews.find(x=>x.start===start&&x.end===end)||{};const md=`# DWK Life OS 周复盘（${start} 至 ${end}）\n\n## 数据汇总\n\n- 周初 / 周末体重：${s.startWeight??'无记录'} / ${s.endWeight??'无记录'} kg（真实记录）\n- 平均体重：${s.avgWeight===null?'无数据':U.number(s.avgWeight)+' kg'}（按真实记录计算）\n- 总支出：${U.formatMoney(s.expense)}；最高分类：${s.topCategory||'无'}\n- Java 学习：${minutes(s.javaMinutes)}\n- 任务完成 / 延期：${s.completedTodos} / ${s.delayedTodos}\n- 骑行 / 油费：${U.number(s.rideKm)} km / ${U.formatMoney(s.fuelCost)}\n- 推进 / 新增点子：${s.advancedIdeas} / ${s.newIdeas}\n\n## 做得好的事情\n${r.good||'未填写'}\n\n## 遇到的问题\n${r.problems||'未填写'}\n\n## 下周最重要的三件事\n${r.topThree||'未填写'}\n\n## 下周停止做\n${r.stopDoing||'未填写'}\n\n## 备注\n${r.notes||'未填写'}\n`;Store.download(`DWK周复盘-${start}.md`,md,'text/markdown');break}
    case'full-export':Store.download(`dwk-life-os-v2-${U.today()}.json`,Store.exportJSON());toast('完整备份已导出');break;case'module-export':openModal('按模块导出',select('module','模块',D.collections,'health'),()=>{const m=val().module;Store.download(`dwk-${m}-${U.today()}.json`,Store.exportJSON(m));closeModal();toast('模块已导出')});break;case'import-open':document.getElementById('importFile').click();break;case'restore-v1':if(confirm('恢复前会自动备份当前第二版数据，确定继续？')){await Store.restoreV1Backup(id);render();toast('第一版备份已恢复并迁移')};break;case'restore-auto':{const raw=localStorage.getItem(id);if(!raw)throw new Error('备份不存在');await Store.importJSON(raw,'replace');render();toast('自动备份已恢复');break}
    case'password-lock':Vault.lock();render();break;case'password-add':passwordModal();break;case'password-edit':passwordModal(Vault.get(id));break;case'password-copy':await navigator.clipboard.writeText(Vault.get(id).password);toast('密码已复制');break;case'password-delete':if(confirm('确定删除加密账户？')){await Vault.remove(id);render()};break;
  }}catch(err){toast(err.message,true)}});
  app.addEventListener('change',e=>{if(e.target.dataset.action==='java-status')commit(d=>get(d.javaTopics,e.target.dataset.id).status=e.target.value,'学习状态已更新')});
  app.addEventListener('submit',async e=>{e.preventDefault();try{if(e.target.id==='reviewRange'){const o=Object.fromEntries(new FormData(e.target).entries());filters.reviewStart=o.start;filters.reviewEnd=o.end;render()}else if(e.target.id==='reviewForm'){const o=Object.fromEntries(new FormData(e.target).entries()),start=filters.reviewStart||U.startOfWeek(),end=filters.reviewEnd||U.dateOffset(6,start);await commit(d=>{const old=d.weeklyReviews.find(x=>x.start===start&&x.end===end),row={...o,id:o.id||U.uid('wr'),start,end,updatedAt:new Date().toISOString()};old?Object.assign(old,row):d.weeklyReviews.push(row)},'周复盘已保存')}else if(e.target.id==='vaultSetup'){const o=Object.fromEntries(new FormData(e.target).entries());if(o.password!==o.confirm)throw new Error('两次主密码不一致');await Vault.setup(o.password);render();toast('密码库已创建')}else if(e.target.id==='vaultUnlock'){await Vault.unlock(new FormData(e.target).get('password'));render();toast('密码库已解锁')}}catch(err){toast(err.message,true)}});
  modalForm.addEventListener('submit',async e=>{e.preventDefault();if(!handler)return;try{await handler();if(!modal.hidden)closeModal()}catch(err){toast(err.message,true)}});
  document.querySelectorAll('.nav-item').forEach(x=>x.addEventListener('click',()=>go(x.dataset.page)));document.getElementById('modalClose').onclick=closeModal;document.getElementById('modalCancel').onclick=closeModal;document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('sidebarOverlay').onclick=()=>document.getElementById('sidebar').classList.remove('open');
  document.getElementById('exportButton').onclick=()=>{Store.download(`dwk-life-os-v2-${U.today()}.json`,Store.exportJSON());toast('完整数据已导出')};document.getElementById('importButton').onclick=()=>document.getElementById('importFile').click();document.getElementById('importFile').onchange=e=>{if(e.target.files[0])importPreview(e.target.files[0]);e.target.value=''};
  document.getElementById('basicSettingsButton').onclick=()=>{const s=Store.get().settings;openModal('基础设置',field('leaveDate','计划离职日期','date',s.leaveDate)+field('monthlyMinCost','每月最低生活费','number',s.monthlyMinCost,'min="0"'),()=>{const o=val();return commit(d=>Object.assign(d.settings,{leaveDate:o.leaveDate,monthlyMinCost:+o.monthlyMinCost}),'基础设置已保存')})};
  document.getElementById('resetButton').onclick=async()=>{if(!confirm('将自动备份当前数据，再载入第二版演示数据。确定继续？'))return;try{await Store.backup('恢复初始前自动备份');await Store.replaceAll(D.createDefaultData(true));render();toast('已恢复演示数据，可在隐私与数据页恢复备份')}catch(err){toast(err.message,true)}};
  document.getElementById('todayText').textContent=new Intl.DateTimeFormat('zh-CN',{dateStyle:'full'}).format(new Date());
  (async()=>{app.innerHTML='<div class="loading">正在初始化本地数据库…</div>';try{await Store.init();page=location.hash.slice(1);if(!UI.titles[page])page='dashboard';render();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(err=>toast('离线服务注册失败：'+err.message,true))}catch(err){app.innerHTML=`<section class="card error-panel"><h2>数据库初始化失败</h2><p>${U.escape(err.message)}</p><p>原 localStorage 数据没有被删除。请关闭其他标签页后刷新，或先导出浏览器站点数据。</p></section>`}})();
})();
