(function(){
  const D=window.DWK_DATA,clone=x=>JSON.parse(JSON.stringify(x)),singletons=['settings','motor'],collections=D.collections;
  const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
  const Store={
    data:null,db:null,lastError:null,
    config(){const defaults=['latestWeight','avg7Weight','change30Weight','availableFunds','budgetRate','supportMonths','mileage','maintenance','javaWeek','javaProgress','leaveCountdown','todayTodos','topIdeas','state7'];try{const saved=JSON.parse(localStorage.getItem(D.CONFIG_KEY)||'{}'),order=[...(saved.dashboardOrder||defaults)];defaults.forEach(k=>{if(!order.includes(k))order.push(k)});return{theme:'dark',hiddenCards:[],...saved,dashboardOrder:order}}catch{return{theme:'dark',dashboardOrder:defaults,hiddenCards:[]}}},
    saveConfig(patch){const next={...this.config(),...patch};localStorage.setItem(D.CONFIG_KEY,JSON.stringify(next));return next},
    open(){return new Promise((resolve,reject)=>{const r=indexedDB.open(D.DB_NAME,D.DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;[...collections,...singletons,'meta'].forEach(name=>{if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'})})};r.onsuccess=()=>{this.db=r.result;resolve(this.db)};r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('数据库被其他页面占用，请关闭其他标签页后重试'))})},
    async readStore(name){return req(this.db.transaction(name).objectStore(name).getAll())},
    async hasData(){const rows=await this.readStore('meta');return rows.some(x=>x.id==='schema')},
    normalizeV1(v1){
      const out=D.createDefaultData(false),motor=v1.motor||{};out.createdAt=new Date().toISOString();out.settings={...out.settings,...(v1.settings||{})};out.accounts=(v1.accounts||out.accounts).map(x=>({...x,receivable:Boolean(x.receivable)}));out.transactions=(v1.transactions||[]).map(x=>({...x,large:Boolean(x.large)}));out.health=(v1.health||[]).map(x=>({...x,water:+x.water||0,steps:+x.steps||0,exerciseMinutes:+x.exerciseMinutes||0,mood:x.mood||x.condition||'一般',cpapUsed:x.cpapUsed??Number(x.cpap)>0,goalCompleted:Boolean(x.goalCompleted)}));out.motor={...out.motor,...motor};out.fuelLogs=motor.fuelLogs||v1.fuelLogs||[];out.maintenanceLogs=motor.maintenanceLogs||v1.maintenanceLogs||[];out.rides=v1.rides||[];out.faults=v1.faults||[];out.repairs=v1.repairs||[];out.javaTopics=(v1.javaTopics||v1.java||out.javaTopics).map(x=>({...x}));out.javaLogs=v1.javaLogs||[];out.ideas=(v1.ideas||[]).map(x=>({interest:3,difficulty:3,estimatedCost:Math.min(5,Math.max(1,Math.ceil((+x.cost||0)/1000)||1)),monetization:3,abilityMatch:3,nextClarity:3,createdAt:x.createdAt||new Date().toISOString(),...x,stage:x.stage==='已完成'?'完成':x.stage,nextAction:x.nextAction||'补充一个可执行的下一步动作'}));out.todos=(v1.todos||[]).map(x=>({...x,status:x.status==='已完成'?'已完成':'未完成',priority:x.priority||'中',module:x.module||'通用',estimatedMinutes:+x.estimatedMinutes||0,actualMinutes:+x.actualMinutes||0,repeat:x.repeat||'无',completedAt:x.completedAt||(x.status==='已完成'?new Date().toISOString():''),delayReason:x.delayReason||''}));['weeklyReviews','fixedExpenses','incomePlans','categoryBudgets'].forEach(k=>out[k]=v1[k]||[]);return out
    },
    v1Backups(){try{return JSON.parse(localStorage.getItem('dwk-life-os-v1-backups')||'[]')}catch{return[]}},
    backupV1(raw){const id='dwk-life-os-v1-backup-'+Date.now(),items=this.v1Backups();localStorage.setItem(id,raw);items.unshift({id,createdAt:new Date().toISOString(),bytes:raw.length});localStorage.setItem('dwk-life-os-v1-backups',JSON.stringify(items.slice(0,10)));return id},
    async migrateV1(raw){const backupId=this.backupV1(raw);try{const parsed=JSON.parse(raw);const migrated=this.normalizeV1(parsed);await this.replaceAll(migrated,{migration:{source:'v1',backupId,at:new Date().toISOString()}});localStorage.setItem('dwk-life-os-migration-v2',JSON.stringify({ok:true,backupId,at:new Date().toISOString()}));return migrated}catch(err){localStorage.setItem('dwk-life-os-migration-v2',JSON.stringify({ok:false,backupId,error:err.message,at:new Date().toISOString()}));throw new Error('第一版数据迁移失败，原数据和迁移前备份均已保留：'+err.message)}},
    async init(){try{await this.open();if(!(await this.hasData())){const raw=localStorage.getItem(D.V1_KEY);this.data=raw?await this.migrateV1(raw):D.createDefaultData(true);if(!raw)await this.replaceAll(this.data)}else this.data=await this.loadAll();window.dispatchEvent(new CustomEvent('dwk:ready'));return this.data}catch(err){this.lastError=err;throw new Error('数据库初始化失败：'+err.message)}},
    async loadAll(){const out={schemaVersion:D.SCHEMA_VERSION};for(const n of collections)out[n]=await this.readStore(n);for(const n of singletons){const row=(await this.readStore(n))[0];out[n]=row?clone(row.value):D.createDefaultData(false)[n]}return out},
    get(){return this.data},
    async replaceAll(data,extraMeta={}){const normalized=data.schemaVersion===2?clone(data):this.normalizeV1(data),names=[...collections,...singletons,'meta'],tx=this.db.transaction(names,'readwrite');for(const n of collections){const s=tx.objectStore(n);s.clear();for(const item of normalized[n]||[])s.put({...item,id:item.id||window.DWK_UTILS.uid(n.slice(0,2))})}for(const n of singletons){const s=tx.objectStore(n);s.clear();s.put({id:n,value:normalized[n]||{}})}const meta=tx.objectStore('meta');meta.clear();meta.put({id:'schema',schemaVersion:2,updatedAt:new Date().toISOString(),...extraMeta});await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('写入中止'))});this.data=normalized;return this.data},
    async update(mutator){const draft=clone(this.data);await mutator(draft);await this.replaceAll(draft);window.dispatchEvent(new CustomEvent('dwk:data-saved'));return this.data},
    async backup(reason='手动备份'){const payload=this.exportObject();const id='dwk-life-os-auto-backup-'+Date.now();localStorage.setItem(id,JSON.stringify(payload));const list=JSON.parse(localStorage.getItem('dwk-life-os-auto-backups')||'[]');list.unshift({id,createdAt:payload.exportedAt,reason});localStorage.setItem('dwk-life-os-auto-backups',JSON.stringify(list.slice(0,5)));list.slice(5).forEach(x=>localStorage.removeItem(x.id));return{id,payload}},
    exportObject(moduleName){const data=moduleName?{[moduleName]:clone(this.data[moduleName])}:clone(this.data);return{app:D.APP,schemaVersion:D.SCHEMA_VERSION,exportedAt:new Date().toISOString(),scope:moduleName||'完整',data,vault:moduleName?undefined:window.DWK_VAULT?.exportEncrypted()||null}},
    exportJSON(moduleName){return JSON.stringify(this.exportObject(moduleName),null,2)},
    validateImport(text){let parsed;try{parsed=typeof text==='string'?JSON.parse(text):text}catch{throw new Error('文件不是有效的 JSON 格式')}const version=Number(parsed.schemaVersion||parsed.version||parsed.data?.schemaVersion||parsed.data?.version||1),data=parsed.data||parsed;if(![1,2].includes(version))throw new Error('不支持的数据版本：'+version);if(!data||typeof data!=='object')throw new Error('数据结构为空');if(version===1){const required=['settings','accounts','transactions','health','motor','java','ideas','todos'];if(required.some(k=>!(k in data)))throw new Error('第一版数据结构不完整')}else if(!parsed.scope||parsed.scope==='完整'){const required=['settings','accounts','transactions','health','motor','javaTopics','ideas','todos'];if(required.some(k=>!(k in data)))throw new Error('第二版完整备份缺少必要模块')}return{parsed,version,data,scope:parsed.scope||'完整',counts:Object.fromEntries(Object.entries(data).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,v.length]))}},
    async importJSON(text,mode='replace'){const check=this.validateImport(text);await this.backup('导入前自动备份');let incoming=check.version===1?this.normalizeV1(check.data):clone(check.data);if(check.scope!=='完整'){const next=clone(this.data);for(const[k,v]of Object.entries(incoming)){if(Array.isArray(v)){const map=new Map((next[k]||[]).map(x=>[x.id,x]));v.forEach(x=>map.set(x.id,x));next[k]=[...map.values()]}}incoming=next}else if(mode==='merge'){const next=clone(this.data);for(const k of collections){const map=new Map((next[k]||[]).map(x=>[x.id,x]));(incoming[k]||[]).forEach(x=>map.set(x.id,x));next[k]=[...map.values()]}next.settings={...next.settings,...incoming.settings};next.motor={...next.motor,...incoming.motor};incoming=next}await this.replaceAll(incoming,{importedAt:new Date().toISOString(),sourceVersion:check.version});if(check.parsed.vault)window.DWK_VAULT?.importEncrypted(check.parsed.vault);return this.data},
    async restoreV1Backup(id){const raw=localStorage.getItem(id);if(!raw)throw new Error('找不到第一版备份');localStorage.setItem(D.V1_KEY,raw);await this.backup('恢复第一版前自动备份');const migrated=this.normalizeV1(JSON.parse(raw));return this.replaceAll(migrated,{restoredFrom:id,at:new Date().toISOString()})},
    download(name,content,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  };
  window.DWK_STORE=Store;
})();
