(function(){
  const DAY=86400000, parseDate=v=>new Date(String(v).slice(0,10)+'T00:00:00');
  const U={
    uid(prefix='id'){return prefix+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,8)},
    today(){const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)},
    dateOffset(days,from){const d=parseDate(from||U.today());d.setDate(d.getDate()+days);return U.localDate(d)},
    localDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)},
    formatDate(v){if(!v)return'—';const d=parseDate(v);return Number.isNaN(d)?v:new Intl.DateTimeFormat('zh-CN').format(d)},
    formatMoney(v){return'¥'+Number(v||0).toLocaleString('zh-CN',{maximumFractionDigits:2})},
    number(v,d=1){const n=Number(v);return Number.isFinite(n)?n.toFixed(d).replace(/\.0+$/,''):'—'},
    escape(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))},
    sum(a,key){return(a||[]).reduce((s,x)=>s+Number(typeof key==='function'?key(x):x[key]||0),0)},
    avg(a,key){return a?.length?U.sum(a,key)/a.length:null}, monthKey(v=U.today()){return String(v).slice(0,7)},
    daysBetween(a,b){return Math.round((parseDate(b)-parseDate(a))/DAY)},
    inRange(date,start,end){return date>=start&&date<=end},
    startOfWeek(v=U.today()){const d=parseDate(v),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return U.localDate(d)},
    workdaysUntil(date){if(!date)return 0;let d=parseDate(U.today()),end=parseDate(date),n=0;while(d<end){d.setDate(d.getDate()+1);if(d.getDay()!==0&&d.getDay()!==6)n++}return n},
    ideaScore(x){const val=k=>Math.min(5,Math.max(1,Number(x[k])||1));return Math.round((val('interest')*.2+val('monetization')*.25+val('abilityMatch')*.2+val('nextClarity')*.2+(6-val('difficulty'))*.1+(6-val('estimatedCost'))*.05)*20)},
    financeStats(d){const available=U.sum(d.accounts.filter(a=>a.available&&!a.refundable&&!a.receivable),'balance'),deposit=U.sum(d.accounts.filter(a=>a.refundable),'balance'),month=d.transactions.filter(t=>t.date.startsWith(U.monthKey())),income=U.sum(month.filter(t=>t.type==='收入'),'amount'),expense=U.sum(month.filter(t=>t.type==='支出'),'amount'),budget=Number(d.settings.monthlyBudget)||0;return{available,deposit,income,expense,budgetRate:budget?expense/budget*100:null,supportMonths:Number(d.settings.monthlyMinCost)?available/Number(d.settings.monthlyMinCost):null}},
    weightRows(d,days){return d.health.filter(x=>x.morningWeight&&U.daysBetween(x.date,U.today())>=0&&U.daysBetween(x.date,U.today())<days).sort((a,b)=>a.date.localeCompare(b.date))},
    closestWeight(d,days){const target=U.dateOffset(-days),rows=d.health.filter(x=>x.morningWeight&&x.date<=target).sort((a,b)=>b.date.localeCompare(a.date));return rows[0]||null},
    weightStats(d){const rows=d.health.filter(x=>x.morningWeight).sort((a,b)=>a.date.localeCompare(b.date)),latest=rows.at(-1),prev=rows.at(-2),r7=U.weightRows(d,7),r30=U.weightRows(d,30),month=rows.filter(x=>x.date.startsWith(U.monthKey())),w7=U.closestWeight(d,7),w30=U.closestWeight(d,30);let streak=0;if(rows.length){let day=rows.at(-1).date;const set=new Set(rows.map(x=>x.date));while(set.has(day)){streak++;day=U.dateOffset(-1,day)}}return{latest:latest?.morningWeight??null,change:latest&&prev?+latest.morningWeight-+prev.morningWeight:null,change7:latest&&w7?+latest.morningWeight-+w7.morningWeight:null,change30:latest&&w30?+latest.morningWeight-+w30.morningWeight:null,avg7:U.avg(r7,'morningWeight'),avg30:U.avg(r30,'morningWeight'),monthMin:month.length?Math.min(...month.map(x=>+x.morningWeight)):null,monthMax:month.length?Math.max(...month.map(x=>+x.morningWeight)):null,streak}},
    javaStats(d){const logs=d.javaLogs||[],minutes=(days)=>U.sum(logs.filter(x=>U.daysBetween(x.date,U.today())>=0&&U.daysBetween(x.date,U.today())<days),'durationMinutes'),done=d.javaTopics.filter(x=>x.status==='已完成').length;return{today:minutes(1),week:U.sum(logs.filter(x=>x.date>=U.startOfWeek()),'durationMinutes'),month:U.sum(logs.filter(x=>x.date.startsWith(U.monthKey())),'durationMinutes'),done,review:d.javaTopics.filter(x=>x.status==='需要复习').length,percent:d.javaTopics.length?Math.round(done/d.javaTopics.length*100):0}},
    motorStats(d){const fuels=[...d.fuelLogs].sort((a,b)=>b.date.localeCompare(a.date)),three=fuels.slice(0,3),calc=a=>{const km=U.sum(a,'mileage'),l=U.sum(a,'liters');return km?l/km*100:null},last=[...d.maintenanceLogs].sort((a,b)=>b.date.localeCompare(a.date))[0],monthRides=d.rides.filter(x=>x.date.startsWith(U.monthKey()));return{avgFuel:calc(fuels),avgFuel3:calc(three),costKm:U.sum(fuels,'mileage')?U.sum(fuels,'amount')/U.sum(fuels,'mileage'):null,monthKm:U.sum(monthRides,'distance'),monthFuel:U.sum(fuels.filter(x=>x.date.startsWith(U.monthKey())),'amount'),maintenanceRemain:last?+last.nextMileage-+d.motor.currentMileage:null,insuranceDays:d.motor.insuranceExpiry?U.daysBetween(U.today(),d.motor.insuranceExpiry):null}},
    isOverdue(t){return t.status!=='已完成'&&t.dueDate&&t.dueDate<U.today()},
    cashFlow(d,scenario='正常'){const f=U.financeStats(d),factor={乐观:.85,正常:1,保守:1.2}[scenario]||1,s=d.settings,monthly=(+s.monthlyNormalCost||0)+(+s.rent||0)+(+s.mortgage||0)+(+s.transportCost||0)+(+s.motorCost||0)+U.sum(d.fixedExpenses,'amount'),income=(+s.expectedIncome||0)+U.sum(d.incomePlans,'amount'),once=U.sum((s.oneTimeExpenses||[]),'amount');let balance=f.available-once;const rows=[];for(let i=1;i<=6;i++){balance+=income-monthly*factor;rows.push({month:U.monthKey(U.dateOffset(i*30)),balance})}const net=monthly*factor-income,months=net>0?Math.max(0,(f.available-once)/net):Infinity;return{scenario,months,exhaustDate:Number.isFinite(months)?U.dateOffset(Math.ceil(months*30)):'可持续增长',rows,riskMonths:rows.filter(x=>x.balance<monthly*factor).map(x=>x.month)}},
    weeklySummary(d,start,end){const health=d.health.filter(x=>U.inRange(x.date,start,end)&&x.morningWeight).sort((a,b)=>a.date.localeCompare(b.date)),tx=d.transactions.filter(x=>U.inRange(x.date,start,end)&&x.type==='支出'),cats={};tx.forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount));const logs=d.javaLogs.filter(x=>U.inRange(x.date,start,end)),todos=d.todos.filter(x=>x.completedAt&&U.inRange(x.completedAt.slice(0,10),start,end)),delayed=d.todos.filter(x=>x.delayReason&&x.dueDate&&U.inRange(x.dueDate,start,end)),rides=d.rides.filter(x=>U.inRange(x.date,start,end)),fuel=d.fuelLogs.filter(x=>U.inRange(x.date,start,end)),ideas=d.ideas.filter(x=>x.updatedAt&&U.inRange(x.updatedAt.slice(0,10),start,end)),newIdeas=d.ideas.filter(x=>x.createdAt&&U.inRange(x.createdAt.slice(0,10),start,end));return{startWeight:health[0]?.morningWeight??null,endWeight:health.at(-1)?.morningWeight??null,avgWeight:U.avg(health,'morningWeight'),expense:U.sum(tx,'amount'),topCategory:Object.entries(cats).sort((a,b)=>b[1]-a[1])[0]?.[0]||null,javaMinutes:U.sum(logs,'durationMinutes'),topics:[...new Set(logs.map(x=>x.content).filter(Boolean))],completedTodos:todos.length,delayedTodos:delayed.length,rideKm:U.sum(rides,'distance'),fuelCost:U.sum(fuel,'amount'),advancedIdeas:ideas.length,newIdeas:newIdeas.length}}
  };
  window.DWK_UTILS=U;
  if(typeof module!=='undefined')module.exports=U;
})();
