server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name 124.220.16.97;

    ssl_certificate /etc/letsencrypt/live/124.220.16.97/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/124.220.16.97/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 1d;
    ssl_session_cache shared:DWKSSL:10m;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy no-referrer always;

    include /etc/nginx/snippets/dwk-life-console.conf;

    location / {
        return 302 /life/;
    }
}
