location = /life {
    return 301 /life/;
}

location ^~ /life/ {
    alias /var/www/dwk-life-console/current/;
    index index.html;
    add_header Cache-Control "no-store, no-cache, must-revalidate" always;
}
